### ISSUE TITLE
minor improvements to committee meetings list on tag page

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#350] opened 2015-06-01 17:32 UTC
###  Reproduction Steps
* goto a tag page (like [this one](https://oknesset.org/tags/%D7%91%D7%98%D7%97%D7%95%D7%9F%20%D7%A4%D7%A0%D7%99%D7%9D/))
* look at the component that displays the committee meetings list

#### Expected
1. when hovering with the mouse cursor over a committee meeting everything gets an underline, including the ocmmittee name and the date, which looks kinda weird (on other lists, only the title gets an underline)
2. plenum meetings also appear and it's also a bit weird - title says "Committee meetings" but then you see a plenum meeting there.
3. if there are a lot of meetings - might need to limit the number of meetings we show there (that's what ofri ment with the more button)

![uploads/db8256f8-c237-4ee6-8cff-458c48abbb89/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb8256f8-c237-4ee6-8cff-458c48abbb89%2Fblob)

**Comment by OriHoch** [comment] 2015-06-01 17:32
@daonb  - FYI..

**Comment by alonisser** [comment] 2016-02-16 07:03
@morchickit  this needs some more defining:
1. UI - what exactly should be displayed with a hovering underline and what not (other similar modules are similar but not the same, so I can't compare ) - This is one issue and should be seperated (as starter and front end)
2. "lot of meetings"  - how many meeting would you like to display? (not front end and perhaps not starter, not sure about what that means) this would be easy. Now for the harder part: what is the expected behavior? a "more meetings" link? that leads where? a new view showing meeting by tags? does it have a design? just show the rest of the meetings in the same page? other?

3." plenum meetings also appear" - again separated bug, but please send me an example tag that demonstrates this, couldn't find one. BTW perhaps this is the correct behavior? where else would tagged plenum meetings be displayed? maybe we just need to change the text

tnx

**Comment by morchickit** [comment] 2016-02-17 11:43
So, i am confused here, because I don't see any of these in the current specific committee list page, besides number 3... 

@OriHoch - can I close this and open new issues?

**Comment by OriHoch** [comment] 2016-02-17 11:54
This issue refers to the tag page ([like this one](https://oknesset.org/tags/%D7%91%D7%98%D7%97%D7%95%D7%9F%20%D7%A4%D7%A0%D7%99%D7%9D/)), I updated the issue description to clarify

This issue is still valid and the bugs occur, if you want to split it into 3 different issues you are welcome to do that..

**Comment by alonisser** [comment] 2016-02-17 12:00
@morchickit  @OriHoch 1. I fixed, 2 I can't find an example for. 

About three I need some definition of what's desired. I can just return the first 10 and if clicks on show more display the rest in the same page..  or move to another page (committee meeting by tags - new or existing page.. ) or .. option one would be the simplest of course but It's really an UX matter

**Comment by OriHoch** [comment] 2016-02-17 12:07
about 2 - I recreated it on [this page](https://oknesset.org/tags/%D7%91%D7%98%D7%97%D7%95%D7%9F%20%D7%A4%D7%A0%D7%99%D7%9D/) - by tagging that plenum meeting with the "בטחון פנים" tag.

![image](https://cloud.githubusercontent.com/assets/1198854/13109053/b8ce9268-d57f-11e5-97be-39b943309bdf.png)

**Comment by OriHoch** [comment] 2016-02-17 12:09
easiest fix for this is just to remove the plenum meetings by adding something like this:
meetings_queryset.exclude(committee__type='plenum')

**Comment by alonisser** [comment] 2016-02-17 12:11
of course, I just wanted to recreate so I can see I fixed it..  :) thanks!



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Closed** 2016-02-22 07:59 UTC
Labels: 4 - Prioritized, Back End, Front End

**Comment by OriHoch** [comment] 2016-02-22 17:41
tested on production, looks good
