### ISSUE TITLE
Votes against party/coalition are wrong

### ISSUE THREAD

**Issue by ofri** [hasadna/Open-Knesset#161] opened 2013-09-30 19:18 UTC
for example, in http://oknesset.org/member/105/%D7%A2%D7%9E%D7%99%D7%A8-%D7%A4%D7%A8%D7%A5/ , click the question mark near משמעת קואליציה and you get a list of votes this MK voted against the coalition. its computed wrong - because in the previous knesset he was in a different party than other MKs in his current party, it is counted as if he voted against them, but they were not really his party/coalition _at the time of those votes_.

**Comment by alonisser** [comment] 2016-02-23 21:50
@OriHoch  @morchickit  I believe this was a duplicate of  #555 (and the related issue) I think this can be safely closed

**Comment by OriHoch** [comment] 2016-02-24 08:58
@morchickit @RacheliRoval please test to make sure it's fixed

**Comment by alonisser** [comment] 2016-11-21 17:23
I believe I already fixed it a long time ago. ALSO the links are not there any more. Closing

**Closed by alonisser** 2016-11-21 17:23 UTC
Labels: 3 - Not prioritized, Back End
